#!/usr/bin/env python
"""
"""

import sys

class Formats:
    HTML = "html"
    TEXT = "txt"

def convert_file(infile, outfile, format=Formats.HTML):
    """Convert from ENEX infile to OUTFILE.

    The default format is Formats.HTML.
    """

    print("Convert {0} to {1}".format(infile, outfile))
    print("format={0}".format(format))

def main(args):
    "Main entry point."

    convert_file(args[1], args[2])

if __name__ == "__main__":
    main(sys.argv)
